### ISSUE TITLE
urlが「https」にすべき？

### ISSUE THREAD

**Issue by lightondust** [ohtaman/tfbook_nlp_samples#2]
scr/preprocess.pyを走らせるとダウンロードだけをして、前処理をしてくれなかった。
どうやらURLが「http」から「https」へ変わったようで
tfbook_nlp_example/src/preprocess.py
の１９行で
`AOZORA_SITE_URL = 'http://www.aozora.gr.jp/'`
となっていて、７６行
```
        if not url.startswith(AOZORA_SITE_URL):
            continue
```
の条件にマッチしなくなったようです。

ドメイン名でマッチングするのがいいと思いますが、お急ぎの場合は単に１９行で
`AOZORA_SITE_URL = 'https://www.aozora.gr.jp/'`
と変えても動きます。

**Comment by ohtaman** [comment]
ご指摘ありがとうございます。
別途PRが来ていました!
